### ISSUE TITLE
latest master does not load /provision endpoint

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-provisioning-app#239]
**ERROR**
**Whitelabel Error Page**
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 01 18:53:49 GMT 2019
There was an unexpected error (type=Internal Server Error, status=500).
No message available

**LOGS**
```
2019-10-01 18:53:49 DEBUG o.o.p.util.rest.RestClientCall - Prepare request for execution
2019-10-01 18:53:49 DEBUG o.o.p.util.rest.RestClientCall - The request has no body
2019-10-01 18:53:49 DEBUG o.o.p.util.rest.RestClientCall - Prepared URL [https://<rundeck>/api/19/project/Quickstarters/jobs?groupPath=quickstarts]
2019-10-01 18:53:49 DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=GET, url=https://<rundeck>/api/19/project/Quickstarters/jobs?groupPath=quickstarts, tag=null}]
2019-10-01 18:53:49 INFO  o.o.provision.util.rest.RestClient - prepare preauthenticated call
2019-10-01 18:53:49 DEBUG o.o.p.util.rest.RestClientCall - Passed parameter map, keys: [[j_password, j_username]]
2019-10-01 18:53:49 DEBUG o.s.web.servlet.DispatcherServlet - Failed to complete request: java.lang.NullPointerException
2019-10-01 18:53:49 DEBUG o.s.s.w.c.HttpSessionSecurityContextRepository - SecurityContext 'org.springframework.security.core.context.SecurityContextImpl@35f17672: Authentication: com.atlassian.crowd.integration.springsecurity.CrowdSSOAuthenticationToken@35f17672: Principal: com.atlassian.crowd.integration.springsecurity.user.CrowdUserDetails@3e864cf4; Credentials: [PROTECTED]; Authenticated: true; Details: com.atlassian.crowd.integration.springsecurity.CrowdSSOAuthenticationDetails@d45f12a7; Granted Authorities: **********' stored to HttpSession: 'org.apache.catalina.session.StandardSessionFacade@5fb71ab5
2019-10-01 18:53:49 DEBUG o.s.s.w.c.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
2019-10-01 18:53:49 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1898)
	at okhttp3.FormBody$Builder.add(FormBody.java:111)
	at org.opendevstack.provision.util.rest.RestClientCall.prepareBody(RestClientCall.java:233)
	at org.opendevstack.provision.util.rest.RestClientCall.getPreauthRequest(RestClientCall.java:249)
	at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:42)
	at org.opendevstack.provision.services.RundeckAdapter.getJobsFromServer(RundeckAdapter.java:254)
	at org.opendevstack.provision.services.RundeckAdapter.initializeJobsForGroup(RundeckAdapter.java:152)
	at org.opendevstack.provision.services.RundeckAdapter.getQuickstarters(RundeckAdapter.java:116)
	at org.opendevstack.provision.controller.DefaultController.provisionProject(DefaultController.java:98)

```

**HYPOTHESIS**
Missing `#Rundeck properties` in prov-app cm.yml

**Comment by gerardcl** [comment]
@stefanlack can you confirm? thanks! let me know if you need help on this! this is urgent for releasing ODS 1.2.x

**Comment by clemensutschig** [comment]
@stefanlack  / @rattermeyer  - we are blocked to test 1.2 ... please help urgently

**Comment by stefanlack** [comment]
Unfortunately, I am not able to reproduce this error. I tested my own production branch wich is very near to master branch, using the oauth-2 profile with external keycloak server.

What authentication are you using? The crowd way, i quess.

BTW: 
- Are you using provision app installed as docker image in openshift?
- Can you prove your HYPOTHESIS by defining missing properties?
- Can you login to the app and see the welcome page? Probably 'yes'. Error occours when you open the provision page, right?

**Comment by clemensutschig** [comment]
`preAuthContent` is null I guess

**Comment by clemensutschig** [comment]
^could it be that you lack the properties:
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/BaseServiceAdapter.java#L40

**Comment by stefanlack** [comment]
Can you please check, if all needed properties are defined, as documented in https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/index.html#_authentication_to_third_party_apps_via_technical_users

**Comment by gerardcl** [comment]
Hi @stefanlack  I confirm we do not have them defined, which values should we provide there? are they coming from ods-configuration also?

**Comment by tjaeschke** [comment]
The technical user properties don't have to be defined. If they are not defined, the manager ones are used: 

`2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.ConfluenceAdapter - configuration prefix confluence
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.ConfluenceAdapter - basic authentication via logged in user is configured, since property confluence.admin_user not defined!
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.JiraAdapter - configuration prefix jira
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.JiraAdapter - basic authentication via logged in user is configured, since property jira.admin_user not defined!
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.RundeckAdapter - configuration prefix rundeck
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.RundeckAdapter - basic authentication via logged in user is configured, since property rundeck.admin_user not defined!
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.BitbucketAdapter - configuration prefix bitbucket
2019-10-02 19:29:39 INFO  o.o.p.services.BaseServiceAdapter - Initialize bean org.opendevstack.provision.services.BitbucketAdapter - basic authentication via logged in user is configured, since property bitbucket.admin_user not defined!`

I think the propertyy Stefan meant is

`provision.auth.provider=crowd`

**Comment by gerardcl** [comment]
Hi @stefanlack  @tjaeschke, 

We already had `provision.auth.provider=crowd` (and I also added `spring.profiles.active=crowd`) indeed, but did not solve the issue yet. 

In the notes I see that `{rundeck,bitbucket,confluence,jira}-admin_{user,password}` credentials are not required since such credentials will be populated by the logged in user ones...but! this is not working in the case of credentials, since they are not populated, but adding `rundeck.-admin{user,password}` with specific credentials it works... is that expected?

**Comment by tjaeschke** [comment]
Hi @gerardcl , 

no, this is not expected and did work the last time I tested it, but since then there has been worked upon the app. I will take a look.
