### ISSUE TITLE
provision comp fails with attempt to checkout ods-quickstarters.git from target repo

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-provisioning-app#298]
**Describe the bug**
Provisioning a component into and existing project 'henpg' fails (provisioned some months ago).
The provisioning app aims to checkout ods-quickstarters from the henpg project. 

**To Reproduce**
1. Go to 'Provision'
2. Select 'Modify existing project'
3. In 'Select existing project' selected my playground project (henpg).
4. In 'Quickstarter' selected 'bePythonFlask'
5. Changed name to a unique name here 'be-python-flask-4'
Pushed 'Start Provision'

Project provision dialog comes up and is green:
A Jenkins job is linked. 

However when going to the Jenkinsjob the job has actually failed. Details see below.

**Expected behavior**
Should provision component.  

**Screenshots**
NA

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [e.g. 1.0, 1.1]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**

```
OpenShift Build henpg-cd/ods-quickstarter-bepythonflask-be-python-flask-4-production-1 from https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git
Checking out git https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git into /var/lib/jenkins/jobs/henpg-cd/jobs/henpg-cd-ods-quickstarter-bepythonflask-be-python-flask-4-production/workspace@script to read be-python-flask/Jenkinsfile
using credential henpg-cd-cd-user-with-password
Cloning the remote Git repository
Cloning repository https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git
 > git init /var/lib/jenkins/jobs/henpg-cd/jobs/henpg-cd-ods-quickstarter-bepythonflask-be-python-flask-4-production/workspace@script # timeout=10
Fetching upstream changes from https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials henpg-cd-cd-user-with-password
 > git fetch --tags --progress https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://cd_user@bitbucket.example.com/scm/henpg/ods-quickstarters.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: remote error: Repository nicht gefunden
Das angeforderte Repository existiert nicht oder Sie sind nicht
zugriffsberechtigt.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2174)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1866)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:78)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:547)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:760)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:149)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Error cloning remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```

**Additional context**

**Comment by michaelsauter** [comment]
@henrjk You will not to update the webhook proxy. In `1.2.x`, it is not allowed to checkout repos outside of your Bitbucket project. In `2.x` it is allowed to checkout `opendevstack` repos too (and any other projects you configure).

**Comment by henrjk** [comment]
After changing the  jenkins-webhoo-proxy's deployment config to use image `cd/jenkins-webhook-proxy:2.x` this worked for me. 

I first got an authentication error about not being able to POST to bitbucket. But after log out and log in this issue went away.
