### ISSUE TITLE
Hardcoded logback path breaks unit tests

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#350]
**Describe the bug**
At least one test fails when running the all tests locally due to a hardcoded path in the logback-spring.xml 

**To Reproduce**
1. Run locally './gradlew clean build'
2. See that at least one test in of ProjectApiControllerTests fails

**Expected behavior**
Unit tests should run successfully independently in which environment they run 

**Affected version (please complete the following information):**
 - Enviroment: local dev env (my ubuntu notebook)
 - OpenDevStack [2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
from ProjectApiControllerTests:
ERROR in ch.qos.logback.core.FileAppender[FILE-logFileName_IS_UNDEFINED] - Failed to create parent directories for [/opt/provision/history/logs/Project.log]
ERROR in ch.qos.logback.core.FileAppender[FILE-logFileName_IS_UNDEFINED] - openFile(/opt/provision/history/logs/Project.log,true) call failed. java.io.FileNotFoundException: /opt/provision/history/logs/Project.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)

```

**Comment by stefanlack** [comment]
I solved this by adding a special spring boot profile (/src/main/resources/application.ci) with a parameter definition

`logging.path=/tmp/workspace/prov-cd/prov-cd-ods-provisioning-app-production/log`

Than you need to do an update on logback-spring.xml and replace

```
	<!-- home of the logs -->
	<property name="PROV_HIST_HOME" value="/opt/provision/history/logs" />
```

with
```
	<springProperty name="springProvHistHome" source="provision.history.home"
		defaultValue="/opt/provision/history/logs"/>
	<!-- home of the logs -->
	<property name="PROV_HIST_HOME" value="${springProvHistHome}" />
```

**Comment by stitakis** [comment]
@stefanlack, thanks for sharing! I think that we need a solution like the one that you proposed. One question, how does ```source="provision.history.home"``` relates to the property ```logging.path``` ?

**Comment by stefanlack** [comment]
@stitakis sorry, I have confused some of the properties. My latest change of the last comment is a partial solution. 
The main idea is that logging configuration property PROV_HIST_HOME points to the spring property provision.history.home, which is literally the same as project.storage.local

The main idea is that logging configuration property PROV_HIST_HOME points to the spring property provision.history.home, which is literally the same as project.storage.local. I can provide this Pull Request maybe tomorrow!

**Comment by stitakis** [comment]
@stefanlack
This is how I solved:
```src/main/resources/application.properties```:
```
logging.file.path=./build/logs
```
src/main/resources/logback-spring.xml
```
	<property name="PROV_HIST_HOME" value="${LOG_PATH}" />
``` 

btw... from my point of view, the default configuration ```application.properties``` should provide a configuration that works locally for most of the configuration. Environment sensitive properties should be defined in its scope properties file. 

We could config logback with ```provision.history.home``` but I prefer to have a default config that works in local environment like the one I defined above with ```logging.file.path```

**Comment by stitakis** [comment]
@stefanlack did you have the chance to take a look at this?

**Comment by stefanlack** [comment]
@stitakis , Yes, your proposal looks good. Do you want to implement this change or sould I do?

**Comment by stitakis** [comment]
@segator I'll implement it and come back to you for review, thanks!
