### ISSUE TITLE
underscore in component name causes provision failure

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#465]
1.  In a new project - create a component named `docker_plain` based on docker plain quickstarter - for some reason the project's webhook proxy secret is not taken, but rather that global trigger secret `openshift` and hence component provisioning fails (401 unauthorized from webhook proxy)

```
org.opendevstack.provision.util.exception.HttpException: Could not POST > https://.../build?trigger_secret=openshift&jenkinsfile_path=delete-components/Jenkinsfile&component=ods-corejob-docker_test  : Not authorized
 Errorcode: 401
	at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:64)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.prepareAndExecuteJob(JenkinsPipelineAdapter.java:348)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.runAdminJob(JenkinsPipelineAdapter.java:542)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.lambda$cleanupQuickstartersOnly$6(JenkinsPipelineAdapter.java:512)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.IntPipeline.reduce(Unknown Source)
	at java.base/java.util.stream.IntPipeline.sum(Unknown Source)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.cleanupQuickstartersOnly(JenkinsPipelineAdapter.java:519)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.cleanup(JenkinsPipelineAdapter.java:485)
	at org.opendevstack.provision.controller.ProjectApiController.cleanup(ProjectApiController.java:901)
	at org.opendevstack.provision.controller.ProjectApiController.updateProject(ProjectApiController.java:448)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

```

For the record, other component names for the same component do work ::)

@metmajer - fyi

**Comment by clemensutschig** [comment]
@stitakis can. You take a look ? Ist only happening with the Name provided above..

**Comment by stitakis** [comment]
@clemensutschig sure, np, I'll take a look asap

**Comment by clemensutschig** [comment]
I took a look - and there is quite some bugs ...
1. why is this an admin job (and not on IN the project) ..

**Comment by stitakis** [comment]
a quick update... at first look... I wasn't able to reproduce with component name `docker-plain`. The UI do not allow to introduce a name that is equal to `quickstarter type`. 
I'll review the code to verify the reason why the project's webhook proxy secret is not taken.

**Comment by michaelsauter** [comment]
@stitakis I think the problem is with an underscore `_`, not hyphen `-` ... ?

**Comment by stitakis** [comment]
@michaelsauter well spotted! Yes, it is `_` the problem... I was able to reproduce now... investigating

**Comment by stitakis** [comment]
@michaelsauter does webhook proxy support component names that include underscore `_` ? Asking because I got this error in the log file when I reproduced.
```
2020-06-23 11:45:17 DEBUG o.o.p.util.rest.SimpleCookieJar - Save cookies for host[webhook-proxy-hello-cd.ocp.odsbox.lan]
2020-06-23 11:45:17 ERROR o.o.provision.util.rest.RestClient - Call failed: 
org.opendevstack.provision.util.exception.HttpException: Could not POST > https://webhook-proxy-hello-cd.ocp.odsbox.lan/build?trigger_secret=************************&jenkinsfile_path=docker-plain/Jenkinsfile&component=ods-qs-docker_plain  : Could not create pipeline
 Errorcode: 422
	at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:64)
	at org.opendevstack.provision.services.JenkinsPipelineAdapter.prepareAndExecuteJob(JenkinsPipelineAdapter.java:348)
	at rg.opendevstack.provision.services.JenkinsPipelineAdapter.provisionComponentsBasedOnQuickstarters(JenkinsPipelineAdapter.java:201)
	at org.opendevstack.provision.controller.ProjectApiController.createDeliveryChain(ProjectApiController.java:580)
	at org.opendevstack.provision.controller.ProjectApiController.updateProject(ProjectApiController.java:414)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

**Comment by michaelsauter** [comment]
422 sounds like it's not valid. Check the logs of the webhook proxy. Also, it would help if the stack trace would include the returned body. Maybe you can just replicate the issue by making a `curl` request against the webhook proxy, then you see the response. The webhook proxy only proxies though, so I suspect that the problem lies with OpenShift not liking the name ...

**Comment by michaelsauter** [comment]
@stitakis Note however that @clemensutschig original post has return code 401, not 422!

**Comment by stitakis** [comment]
@michaelsauter
- webhook-proxy logs do not show anything, how can I enable `debug` mode?
- yes, I noticed that clemens posted error returned 401. It is a different one and it is related to POST delete-components pipeline... smells like a different bug. I'll investigate this one too.

**Comment by michaelsauter** [comment]
> webhook-proxy logs do not show anything, how can I enable debug mode?

There is no debug mode. However, you should see logs for any request. Also, instances based on `master` might show some more logs than `2.x` based ones ... that said, since you get 422 returned, you should be able to get the body too, which will help you find the issue.

**Comment by stitakis** [comment]
@michaelsauter for some reason (bad internet connection probably) I wasn't able to see the webhook proxy but I see it now. This is the error:

**Comment by stitakis** [comment]
I've created this issues #474 for the other bug

**Comment by michaelsauter** [comment]
@stitakis Sounds good, let's prevent underscores in component names in the prov app.
