### ISSUE TITLE
session timeout too short for project provision on enterprise environment

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#622]
Provision of project from the UI is failing due to too short session timeout.
The current session timeout is set to 7 minutes.
The action of log into the UI and the fill the create project form could take maybe 3 mins.
The provision process could take up to 5 minutes in enterprise environment to complete.
In this case the session will expire in the middle of the provisioning causing a exception because credentials are removed from the scope.

Ie.: 
2020-10-21 14:58:13 loggerFileName=****** [http-nio-8080-exec-4] ERROR o.o.p.c.ProjectApiController - An error occured while creating project [********], reason [Not able t
o create credentials info!] - cleanup attempted, but [\{BUGTRACKER_PROJECT=1}] components are still there!
org.opendevstack.provision.authentication.MissingCredentialsInfoException: Not able to create credentials info!
        at org.opendevstack.provision.services.BaseServiceAdapter.authenticatedCall(BaseServiceAdapter.java:118)
        at org.opendevstack.provision.services.BaseServiceAdapter.httpGet(BaseServiceAdapter.java:92)
        at org.opendevstack.provision.services.ConfluenceAdapter.getSpaceTemplateList(ConfluenceAdapter.java:224)

Solution:
- we need to increase the timeout.
- additionally we need to add more logging message to track this kind of situations to be able to understand when an exception of this kind is raised.

**Comment by michaelsauter** [comment]
As #623 has been merged, can we close this one @stitakis?

**Comment by stitakis** [comment]
I need to port this change to master before closing it
