### ISSUE TITLE
Creation of Bitbucket project fails in case of long description (~480 chars) - causing downstream  NPE

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#64]
2018-11-28 10:47:19 loggerFileName=BRASS [http-nio-8080-exec-4] DEBUG o.o.p.services.BitbucketAdapter - https://...../rest/api/1.0/projects/**null**/permissions/groups?permission=PROJECT_WRITE&name=BI-dDevstack-Users - 404>{"errors":[{"context":null,"message":"Project null does not exist.","exceptionName":"com.atlassian.bitbucket.project.NoSuchProjectException"}]}
2018-11-28 10:47:20 loggerFileName=BRASS [http-nio-8080-exec-4] ERROR o.o.p.c.ProjectApiController - An error occured while provisioning project: {}
java.lang.NullPointerException: null
        at org.opendevstack.provision.services.BitbucketAdapter.createBitbucketProjectsForProject(BitbucketAdapter.java:126)
        at org.opendevstack.provision.controller.ProjectApiController.createDeliveryChain(ProjectApiController.java:286)
        at org.opendevstack.provision.controller.ProjectApiController.addProject(ProjectApiController.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by clemensutschig** [comment]
@sgolms - fix in progress :)
